"""
Knowledge Graph Embedding Generator — Multi-Book Edition
=========================================================

Takes the JSON files generated by ingest.py (from all 5 books) and creates
dense vector embeddings for both the unique words (nodes) and paragraphs.

Usage:
    python -m knowledge.ingest_embeddings
"""

import json
import os
import torch
from sentence_transformers import SentenceTransformer

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
MODEL_NAME = "all-MiniLM-L6-v2"


def main():
    print(f"\nGenerating Embeddings using {MODEL_NAME}...")
    print("=" * 60)

    # 1. Load the model
    print("[1/4] Loading Sentence Transformer model...")
    model = SentenceTransformer(MODEL_NAME)

    # 2. Load JSON data
    print("[2/4] Loading paragraphs and graph...")
    with open(os.path.join(DATA_DIR, "paragraphs.json"), "r") as f:
        paragraphs = json.load(f)

    with open(os.path.join(DATA_DIR, "graph.json"), "r") as f:
        graph = json.load(f)

    # Handle both old format (list of strings) and new format (list of dicts)
    if paragraphs and isinstance(paragraphs[0], dict):
        para_texts = [p["text"] for p in paragraphs]
        print(f"  Loaded {len(paragraphs)} paragraphs from multiple books")

        # Print per-book counts
        from collections import Counter
        source_counts = Counter(p["source"] for p in paragraphs)
        for source, count in sorted(source_counts.items()):
            print(f"    - {source}: {count} paragraphs")
    else:
        para_texts = paragraphs
        print(f"  Loaded {len(paragraphs)} paragraphs")

    # 3. Embed Nodes (graph words)
    unique_words = list(graph.keys())
    print(f"[3/4] Generating embeddings for {len(unique_words)} unique graph nodes...")
    node_embs = model.encode(unique_words, convert_to_tensor=True, show_progress_bar=True)
    node_embed_dict = {w: node_embs[i].cpu() for i, w in enumerate(unique_words)}

    node_path = os.path.join(DATA_DIR, "node_embeddings.pt")
    torch.save(node_embed_dict, node_path)
    print(f"  -> Saved to {node_path}")

    # 4. Embed Paragraphs
    print(f"[4/4] Generating embeddings for {len(para_texts)} paragraphs...")
    para_embs = model.encode(para_texts, convert_to_tensor=True, show_progress_bar=True)

    para_path = os.path.join(DATA_DIR, "paragraph_embeddings.pt")
    torch.save(para_embs.cpu(), para_path)
    print(f"  -> Saved to {para_path}")

    print("\n" + "=" * 60)
    print("All embeddings generated successfully!")
    print("=" * 60)


if __name__ == "__main__":
    main()
